// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using exam_service.Infrastructure.Persistence;

#nullable disable

namespace exam_service.Migrations
{
    [DbContext(typeof(ExamDbContext))]
    [Migration("20251119090000_AddSectionAudioFields")]
    partial class AddSectionAudioFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("exam_service.Domains.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DescriptionMd")
                        .HasColumnType("text");

                    b.Property<int>("DurationMin")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("exam_service.Domains.Entities.ExamOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentMd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Idx")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "Idx");

                    b.ToTable("exam_options", (string)null);
                });

            modelBuilder.Entity("exam_service.Domains.Entities.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, string[]?>>("BlankAcceptRegex")
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, string[]?>>("BlankAcceptTexts")
                        .HasColumnType("jsonb");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("ExplanationMd")
                        .HasColumnType("text");

                    b.Property<int>("Idx")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, string[]?>>("MatchPairs")
                        .HasColumnType("jsonb");

                    b.Property<List<string>>("OrderCorrects")
                        .HasColumnType("text[]");

                    b.Property<string>("PromptMd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<List<string>>("ShortAnswerAcceptRegex")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("ShortAnswerAcceptTexts")
                        .HasColumnType("text[]");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SectionId", "Idx");

                    b.ToTable("exam_questions", (string)null);
                });

            modelBuilder.Entity("exam_service.Domains.Entities.ExamSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Idx")
                        .HasColumnType("integer");

                    b.Property<string>("InstructionsMd")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranscriptMd")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamId", "Idx");

                    b.ToTable("exam_sections", (string)null);
                });

            modelBuilder.Entity("exam_service.Domains.Entities.ExamOption", b =>
                {
                    b.HasOne("exam_service.Domains.Entities.ExamQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("exam_service.Domains.Entities.ExamQuestion", b =>
                {
                    b.HasOne("exam_service.Domains.Entities.ExamSection", "Section")
                        .WithMany("Questions")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("exam_service.Domains.Entities.ExamSection", b =>
                {
                    b.HasOne("exam_service.Domains.Entities.Exam", "Exam")
                        .WithMany("Sections")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("exam_service.Domains.Entities.Exam", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("exam_service.Domains.Entities.ExamQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("exam_service.Domains.Entities.ExamSection", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
