// <auto-generated />
using System;
using System.Text.Json;
using ExamService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace exam_service.Migrations
{
    [DbContext(typeof(ExamDbContext))]
    partial class ExamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamService.Domains.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DescriptionMd")
                        .HasColumnType("text");

                    b.Property<int>("DurationMin")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("ExamService.Domains.Entities.ExamOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentMd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Idx")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "Idx");

                    b.ToTable("exam_options", (string)null);
                });

            modelBuilder.Entity("ExamService.Domains.Entities.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ExamQuestionGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExamSectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Idx")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("1.0.0");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CorrectAnswer")
                        .HasDatabaseName("ix_exam_questions_correct_answer_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CorrectAnswer"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("CorrectAnswer"), new[] { "jsonb_path_ops" });

                    b.HasIndex("ExamQuestionGroupId");

                    b.HasIndex("ExamSectionId");

                    b.HasIndex("GroupId");

                    b.HasIndex("Payload")
                        .HasDatabaseName("ix_exam_questions_payload_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Payload"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Payload"), new[] { "jsonb_path_ops" });

                    b.HasIndex("SectionId", "Idx")
                        .IsUnique();

                    b.ToTable("exam_questions", (string)null);
                });

            modelBuilder.Entity("ExamService.Domains.Entities.ExamQuestionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EndIdx")
                        .HasColumnType("integer");

                    b.Property<int>("Idx")
                        .HasColumnType("integer");

                    b.Property<string>("InstructionMd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<int>("StartIdx")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SectionId", "Idx")
                        .IsUnique();

                    b.ToTable("exam_question_groups", (string)null);
                });

            modelBuilder.Entity("ExamService.Domains.Entities.ExamSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Idx")
                        .HasColumnType("integer");

                    b.Property<string>("InstructionsMd")
                        .HasColumnType("text");

                    b.Property<string>("PassageMd")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranscriptMd")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamId", "Idx")
                        .IsUnique();

                    b.ToTable("exam_sections", (string)null);
                });

            modelBuilder.Entity("ExamService.Domains.Entities.ExamOption", b =>
                {
                    b.HasOne("ExamService.Domains.Entities.ExamQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ExamService.Domains.Entities.ExamQuestion", b =>
                {
                    b.HasOne("ExamService.Domains.Entities.ExamQuestionGroup", null)
                        .WithMany("Questions")
                        .HasForeignKey("ExamQuestionGroupId");

                    b.HasOne("ExamService.Domains.Entities.ExamSection", null)
                        .WithMany("Questions")
                        .HasForeignKey("ExamSectionId");

                    b.HasOne("ExamService.Domains.Entities.ExamQuestionGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExamService.Domains.Entities.ExamSection", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ExamService.Domains.Entities.ExamQuestionGroup", b =>
                {
                    b.HasOne("ExamService.Domains.Entities.ExamSection", "Section")
                        .WithMany("QuestionGroups")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ExamService.Domains.Entities.ExamSection", b =>
                {
                    b.HasOne("ExamService.Domains.Entities.Exam", "Exam")
                        .WithMany("Sections")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("ExamService.Domains.Entities.Exam", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ExamService.Domains.Entities.ExamQuestionGroup", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ExamService.Domains.Entities.ExamSection", b =>
                {
                    b.Navigation("QuestionGroups");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
