// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using speaking_service.Infrastructure.Persistence;

#nullable disable

namespace speaking_service.Migrations
{
    [DbContext(typeof(SpeakingDbContext))]
    [Migration("20251121172611_InitSpeakingDb")]
    partial class InitSpeakingDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("speaking_service.Domains.Entities.SpeakingEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FluencyAndCoherenceBand")
                        .HasColumnType("double precision");

                    b.Property<string>("FluencyAndCoherenceComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GrammaticalRangeAndAccuracyBand")
                        .HasColumnType("double precision");

                    b.Property<string>("GrammaticalRangeAndAccuracyComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImprovedAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("LexicalResourceBand")
                        .HasColumnType("double precision");

                    b.Property<string>("LexicalResourceComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OverallBand")
                        .HasColumnType("double precision");

                    b.Property<string>("PromptSchemaVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PronunciationBand")
                        .HasColumnType("double precision");

                    b.Property<string>("PronunciationComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawLlmJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuggestionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("speaking_evaluations", (string)null);
                });

            modelBuilder.Entity("speaking_service.Domains.Entities.SpeakingExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("ExamType")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("TaskText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("speaking_exams", (string)null);
                });

            modelBuilder.Entity("speaking_service.Domains.Entities.SpeakingSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExamType")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaskTextSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TimeSpentSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("TranscriptNormalized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranscriptRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("speaking_submissions", (string)null);
                });

            modelBuilder.Entity("speaking_service.Domains.Entities.SpeakingEvaluation", b =>
                {
                    b.HasOne("speaking_service.Domains.Entities.SpeakingSubmission", "SpeakingSubmission")
                        .WithMany("SpeakingEvaluations")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpeakingSubmission");
                });

            modelBuilder.Entity("speaking_service.Domains.Entities.SpeakingSubmission", b =>
                {
                    b.HasOne("speaking_service.Domains.Entities.SpeakingExam", "SpeakingExam")
                        .WithMany("SpeakingSubmissions")
                        .HasForeignKey("ExamId");

                    b.Navigation("SpeakingExam");
                });

            modelBuilder.Entity("speaking_service.Domains.Entities.SpeakingExam", b =>
                {
                    b.Navigation("SpeakingSubmissions");
                });

            modelBuilder.Entity("speaking_service.Domains.Entities.SpeakingSubmission", b =>
                {
                    b.Navigation("SpeakingEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
