<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.3.2" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableHotReload>true</EnableHotReload>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" Version="13.3.2" />
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.3.2" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.3.2" />
    <PackageReference Include="Aspire.Npgsql" Version="13.3.2" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.3.2" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.3.2" />
    <PackageReference Include="Aspire.Hosting.Docker" Version="13.3.2" />
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.5.2" />
    <PackageReference Include="CommunityToolkit.Aspire.MassTransit.RabbitMQ" Version="13.3.0" />
  </ItemGroup>

  <ItemGroup>
    <AppHostProjectReference Include="..\gateway\api-gateway\api-gateway.csproj" />
    <AppHostProjectReference Include="..\services\exam-service\exam-service.csproj" />
    <AppHostProjectReference Include="..\services\gamification-service\gamification-service.csproj" />
    <AppHostProjectReference Include="..\services\speaking-service\speaking-service.csproj" />
    <AppHostProjectReference Include="..\services\dictionary-service\dictionary-service.csproj" />
    <AppHostProjectReference Include="..\services\attempt-service\attempt-service.csproj" />
    <AppHostProjectReference Include="..\services\auth-service\auth-service.csproj" />
    <AppHostProjectReference Include="..\services\course-service\course-service.csproj" />
    <AppHostProjectReference Include="..\services\email-service\email-service.csproj" />
    <AppHostProjectReference Include="..\services\vocabulary-service\vocabulary-service.csproj" />
    <AppHostProjectReference Include="..\services\writing-service\writing-service.csproj" />
  </ItemGroup>

</Project>