BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DELETE FROM exam_options WHERE "QuestionId" IN (
  SELECT q."Id" FROM exam_questions q
  JOIN exam_sections s ON s."Id" = q."SectionId"
  JOIN exams e ON e."Id" = s."ExamId"
  WHERE e."Slug" = 'ielts-reading-photovoltaics-on-the-rooftop-1369'
);
DELETE FROM exam_questions USING exam_sections s, exams e
WHERE exam_questions."SectionId" = s."Id"
  AND s."ExamId" = e."Id"
  AND e."Slug" = 'ielts-reading-photovoltaics-on-the-rooftop-1369';
DELETE FROM exam_sections USING exams e
WHERE exam_sections."ExamId" = e."Id"
  AND e."Slug" = 'ielts-reading-photovoltaics-on-the-rooftop-1369';
DELETE FROM exams WHERE "Slug" = 'ielts-reading-photovoltaics-on-the-rooftop-1369';

INSERT INTO exams ("Id","Slug","Title","DescriptionMd","Category","Level","Status","DurationMin","CreatedAt")
VALUES ('23e657e9-a847-55db-b9e0-7a01b6301155', 'ielts-reading-photovoltaics-on-the-rooftop-1369', $t$Photovoltaics on the rooftop$t$, $md$## Photovoltaics on the rooftop

Nguồn:
- Test: https://mini-ielts.com/1369/reading/photovoltaics-on-the-rooftop
- Solution: https://mini-ielts.com/1369/view-solution/reading/photovoltaics-on-the-rooftop$md$, 'IELTS', 'B2', 'PUBLISHED', 20, now());

INSERT INTO exam_sections ("Id","ExamId","Idx","Title","InstructionsMd","AudioUrl","TranscriptMd")
VALUES ('6db6fd40-872e-558d-8e71-dd400cda2317', '23e657e9-a847-55db-b9e0-7a01b6301155', 1, $t$Reading — Photovoltaics on the rooftop$t$, $md$Read the passage and answer questions **1–13**.

### Passage: Photovoltaics on the rooftop

A

In the past, urban homeowners have not always had much choice in the way electricity is supplied to their homes. Now, however, there is a choice, and a rapidly increasing number of households worldwide are choosing the solar energy option. Solar energy, the conversion of sunlight into energy, is made possible through the use of ‘photovoltaics’, which are simple appliances that fit onto the roof of a house.

B

The photovoltaics-powered home remains connected to the power lines, but no storage is required on-site, only a box of electronics (the inverter) to the interface between the photovoltaics and the grid network. Figure 1 illustrates the system. During the day, when the home may not be using much electricity, excess power from the solar array is fed back to the grid, to factories and offices that need daytime power. At night, power flows the opposite way. The grid network effectively provides storage. If the demand for electricity is well matched to when the sun shines, solar energy is especially valuable. This occurs in places like California in the US and Japan, where air-conditioning loads for offices and factories are large but heating loads for homes are small.

C

The first systematic exploration of the use of photovoltaics on homes began in the US during the 1970s. A well-conceived program started with the sitting of a number of residential experiment stations’ at selected locations around the country, representing different climatic zones. These stations contained a number of ‘dummy’ houses, each with different solar-energy system design. Homes within the communities close to these stations were monitored to see how well their energy use matched the energy generated by the stations’ dummy roofs. A change in US government priorities in the early 1980s halted this program.

D

With the US effort dropping away, the Japanese Sunshine Project came to the fore. A large residential test station was installed on Rokko Island beginning in 1986. This installation consists of 18 ‘dummy’ homes. Each equipped with its own 2-5 kilowatt photovoltaic system (about 20 – 50 square meters for each system). Some of these simulated homes have their own electrical appliances inside, such as TV sets, refrigerators and air conditioning units, which switch on and off under computer control providing a lavish lifestyle for the non-existent occupants. For the other systems, electronics simulate these household loads. This test station has allowed being explored in a systematic way, under well-controlled test conditions. With no insurmountable problems identified, the Japanese have used the experience gained from this station to begin their own massive residential photovoltaics campaign.

E

Meanwhile, Germany began a very important ‘1,000 roof program’ in 1990, aimed at installing photovoltaics on the roofs of 1,000 private homes. Large federal and regional government subsidies were involved, accounting in most cases for 70% of the total system costs. The program proved immensely popular, forcing its extension to over 2,000 homes scattered across Germany. The success of this program stimulated other European countries to launch a similar program.

F

Japan’s ‘one million roof program’ was prompted by the experience gained in the Rokko Island test site and the success of the German 1,000 roof program. The initially quoted aims of the Japanese New Energy Development Organization were to have 70,000 homes equipped with the photovoltaics by the year 2000, on the way to 1 million by 2010. The program made a modest start in 1994 when 539 systems were installed with a government subsidy of 50 percent. Under this program, entire new suburban developments are using photovoltaics.

G

This is good news, not only for the photovoltaic industry but for everyone concerned with the environment. The use of fossil fuels to generate electricity is not only costly in financial terms, but also in terms of environmental damage. Gases produced by the burning of fossil fuels in the production of electricity are a major contributor to the greenhouse effect. To deal with this problem, many governments are now proposing stringent targets on the amount of greenhouse gas emissions permitted. These targets mean that all sources of greenhouse gas emissions including residential electricity use will receive closer attention in the future.

H

It is likely that in the future, governments will develop building codes that attempt to constrain the energy demands of new housing. For example, the use of photovoltaics or the equivalent may be stipulated to lessen demands on the grid network and hence reduce fossil fuel emissions. Approvals for building renovations may also be conditional upon taking such energy-saving measures. If this were to happen, everyone would benefit. Although there is an initial cost in attaching the system to the rooftop, the householder’s outlay is soon compensated with the savings on energy bills. In addition, everyone living on the planet stands to gain from the more benign environmental impact.$md$, NULL, NULL);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('17a561c4-1c4c-5a3b-8fa3-0a0b396af8a7', '6db6fd40-872e-558d-8e71-dd400cda2317', 1, 'MATCHING_INFORMATION', 'READING', 2, $md$### Question 1

Questions 1-6
Questions 1-6
The Reading Passage has nine paragraphs
A-H
Which paragraph contains the following information?
Write the correct letter
A-H
, in boxes
1-6
on your answer sheet.
NB
You may use any letter more than once.
1
examples of countries where electricity use is greater during the day than at night
2
a detailed description of an experiment that led to photovoltaics being promoted throughout the country
3
the negative effects of using conventional means of generating electricity
4
an explanation of the photovoltaic system.
5
the long-term benefits of using photovoltaics
6
a large campaign inspired by a country's successful example

1 ____ examples of countries where electricity use is greater during the day than at night$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('b0040ece-fd41-56b3-9b55-21b6654d8609', '17a561c4-1c4c-5a3b-8fa3-0a0b396af8a7', 1, $md$A$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('43dedad0-aca4-523f-804c-bf5aa9a5a97a', '17a561c4-1c4c-5a3b-8fa3-0a0b396af8a7', 2, $md$B$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('1eb70708-b9ed-57f8-902a-7dca527d5cd3', '17a561c4-1c4c-5a3b-8fa3-0a0b396af8a7', 3, $md$C$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('1b5fef57-fc3d-50ee-a836-32311c787f80', '17a561c4-1c4c-5a3b-8fa3-0a0b396af8a7', 4, $md$D$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('422ef35a-61f0-5996-9693-3709a430cc39', '17a561c4-1c4c-5a3b-8fa3-0a0b396af8a7', 5, $md$E$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('ce9b6479-a1c6-57bd-af5b-9a208be46279', '17a561c4-1c4c-5a3b-8fa3-0a0b396af8a7', 6, $md$F$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('27781d00-9845-5473-988e-20352b796f39', '17a561c4-1c4c-5a3b-8fa3-0a0b396af8a7', 7, $md$G$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('a0377164-7359-50f0-a081-54b96c2bbbe7', '17a561c4-1c4c-5a3b-8fa3-0a0b396af8a7', 8, $md$H$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('380937d5-4157-5c15-96c9-be5d85fd21c0', '6db6fd40-872e-558d-8e71-dd400cda2317', 2, 'MATCHING_INFORMATION', 'READING', 2, $md$### Question 2

Questions 1-6
Questions 1-6
The Reading Passage has nine paragraphs
A-H
Which paragraph contains the following information?
Write the correct letter
A-H
, in boxes
1-6
on your answer sheet.
NB
You may use any letter more than once.
1
examples of countries where electricity use is greater during the day than at night
2
a detailed description of an experiment that led to photovoltaics being promoted throughout the country
3
the negative effects of using conventional means of generating electricity
4
an explanation of the photovoltaic system.
5
the long-term benefits of using photovoltaics
6
a large campaign inspired by a country's successful example

2 ____ a detailed description of an experiment that led to photovoltaics being promoted throughout the country$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('e209a27f-ec5a-580f-849f-7f0c244bec9f', '380937d5-4157-5c15-96c9-be5d85fd21c0', 1, $md$A$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('0d3a14f5-ce0b-523e-bcbf-3aea5ca64d9b', '380937d5-4157-5c15-96c9-be5d85fd21c0', 2, $md$B$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('0a02fb10-1cc0-5e1d-936a-beebd9c4856f', '380937d5-4157-5c15-96c9-be5d85fd21c0', 3, $md$C$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('2c9d187d-effb-5427-a113-30d8c7a8b4a9', '380937d5-4157-5c15-96c9-be5d85fd21c0', 4, $md$D$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('decf2622-2663-53cd-beeb-06e2cc9fb119', '380937d5-4157-5c15-96c9-be5d85fd21c0', 5, $md$E$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('80102808-159f-5e2e-901d-59621f5ae157', '380937d5-4157-5c15-96c9-be5d85fd21c0', 6, $md$F$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('66fbab50-93ac-5467-83d7-5c6af0acbe65', '380937d5-4157-5c15-96c9-be5d85fd21c0', 7, $md$G$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('e7cbd9a7-e4aa-5d2f-b3d4-e1e43cf6b6f2', '380937d5-4157-5c15-96c9-be5d85fd21c0', 8, $md$H$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('5c8b472d-5114-5600-b950-cd1a3d07382e', '6db6fd40-872e-558d-8e71-dd400cda2317', 3, 'MATCHING_INFORMATION', 'READING', 2, $md$### Question 3

Questions 1-6
Questions 1-6
The Reading Passage has nine paragraphs
A-H
Which paragraph contains the following information?
Write the correct letter
A-H
, in boxes
1-6
on your answer sheet.
NB
You may use any letter more than once.
1
examples of countries where electricity use is greater during the day than at night
2
a detailed description of an experiment that led to photovoltaics being promoted throughout the country
3
the negative effects of using conventional means of generating electricity
4
an explanation of the photovoltaic system.
5
the long-term benefits of using photovoltaics
6
a large campaign inspired by a country's successful example

3 ____ the negative effects of using conventional means of generating electricity$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('1dea9ede-30dd-55fd-bbae-1ac4a5995b0a', '5c8b472d-5114-5600-b950-cd1a3d07382e', 1, $md$A$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('d1c145ff-f7f2-5ad4-8820-5e9b2927053d', '5c8b472d-5114-5600-b950-cd1a3d07382e', 2, $md$B$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('19bfdc18-182a-59d0-b379-556149019fa6', '5c8b472d-5114-5600-b950-cd1a3d07382e', 3, $md$C$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('d0fe3d77-614b-5f0f-a04e-563bc8f074cc', '5c8b472d-5114-5600-b950-cd1a3d07382e', 4, $md$D$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('a8c1281d-ee64-54ad-bc6f-58496a3beb95', '5c8b472d-5114-5600-b950-cd1a3d07382e', 5, $md$E$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('9948f2d3-8c62-5aef-b138-bf0e122aa78d', '5c8b472d-5114-5600-b950-cd1a3d07382e', 6, $md$F$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('e4a1ab92-237b-5617-a108-05fe7d68aa7f', '5c8b472d-5114-5600-b950-cd1a3d07382e', 7, $md$G$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('ea49585e-a7e0-5677-ac56-930e77b7ddb5', '5c8b472d-5114-5600-b950-cd1a3d07382e', 8, $md$H$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('dc141d17-0a0e-58ec-89af-03e24913b085', '6db6fd40-872e-558d-8e71-dd400cda2317', 4, 'MATCHING_INFORMATION', 'READING', 2, $md$### Question 4

Questions 1-6
Questions 1-6
The Reading Passage has nine paragraphs
A-H
Which paragraph contains the following information?
Write the correct letter
A-H
, in boxes
1-6
on your answer sheet.
NB
You may use any letter more than once.
1
examples of countries where electricity use is greater during the day than at night
2
a detailed description of an experiment that led to photovoltaics being promoted throughout the country
3
the negative effects of using conventional means of generating electricity
4
an explanation of the photovoltaic system.
5
the long-term benefits of using photovoltaics
6
a large campaign inspired by a country's successful example

4 ____ an explanation of the photovoltaic system.$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('927efb81-5e29-500a-a9f2-8a499c6d92a8', 'dc141d17-0a0e-58ec-89af-03e24913b085', 1, $md$A$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('066b2a95-f8c3-57ca-a435-8ea6eacfb4ed', 'dc141d17-0a0e-58ec-89af-03e24913b085', 2, $md$B$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('a4b1cde1-4ab9-59f0-b937-aa7fde005c02', 'dc141d17-0a0e-58ec-89af-03e24913b085', 3, $md$C$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('ce95ae91-417b-592d-9990-1795d267f120', 'dc141d17-0a0e-58ec-89af-03e24913b085', 4, $md$D$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('2d227577-b79c-525b-a165-f52eebae5ee7', 'dc141d17-0a0e-58ec-89af-03e24913b085', 5, $md$E$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('dfccf480-271b-5458-aaf6-d91503cde78b', 'dc141d17-0a0e-58ec-89af-03e24913b085', 6, $md$F$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('fb203fb7-d87c-5d9c-8e87-00ab08393b64', 'dc141d17-0a0e-58ec-89af-03e24913b085', 7, $md$G$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('da77cc3c-a917-5df7-8c80-7a54618135dc', 'dc141d17-0a0e-58ec-89af-03e24913b085', 8, $md$H$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('4bd9e722-a8d6-514a-91cf-badd437f26e2', '6db6fd40-872e-558d-8e71-dd400cda2317', 5, 'MATCHING_INFORMATION', 'READING', 3, $md$### Question 5

Questions 1-6
Questions 1-6
The Reading Passage has nine paragraphs
A-H
Which paragraph contains the following information?
Write the correct letter
A-H
, in boxes
1-6
on your answer sheet.
NB
You may use any letter more than once.
1
examples of countries where electricity use is greater during the day than at night
2
a detailed description of an experiment that led to photovoltaics being promoted throughout the country
3
the negative effects of using conventional means of generating electricity
4
an explanation of the photovoltaic system.
5
the long-term benefits of using photovoltaics
6
a large campaign inspired by a country's successful example

5 ____ the long-term benefits of using photovoltaics$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('87522df8-786f-536d-847b-bb9d4175edfd', '4bd9e722-a8d6-514a-91cf-badd437f26e2', 1, $md$A$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('04ac287a-79d7-5df3-8fcd-5df014f0dae3', '4bd9e722-a8d6-514a-91cf-badd437f26e2', 2, $md$B$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('f93e64a1-f9b2-5084-8d86-4ffbc2ed9786', '4bd9e722-a8d6-514a-91cf-badd437f26e2', 3, $md$C$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('bb44b465-948a-573d-a5db-e5fe29280241', '4bd9e722-a8d6-514a-91cf-badd437f26e2', 4, $md$D$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('f3005e09-462c-5e46-b5dd-9684ed6d805c', '4bd9e722-a8d6-514a-91cf-badd437f26e2', 5, $md$E$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('335bb5b0-a9c1-5bd9-8820-e7421b029c52', '4bd9e722-a8d6-514a-91cf-badd437f26e2', 6, $md$F$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('0fd47ec0-6bb6-54b4-b19c-0ff22c6fc344', '4bd9e722-a8d6-514a-91cf-badd437f26e2', 7, $md$G$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('04b9aa61-24f1-5589-9565-cb41b52fd0d7', '4bd9e722-a8d6-514a-91cf-badd437f26e2', 8, $md$H$md$, true);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('2639c4ff-e189-5688-bc06-6d0839e18805', '6db6fd40-872e-558d-8e71-dd400cda2317', 6, 'MATCHING_INFORMATION', 'READING', 3, $md$### Question 6

Questions 1-6
Questions 1-6
The Reading Passage has nine paragraphs
A-H
Which paragraph contains the following information?
Write the correct letter
A-H
, in boxes
1-6
on your answer sheet.
NB
You may use any letter more than once.
1
examples of countries where electricity use is greater during the day than at night
2
a detailed description of an experiment that led to photovoltaics being promoted throughout the country
3
the negative effects of using conventional means of generating electricity
4
an explanation of the photovoltaic system.
5
the long-term benefits of using photovoltaics
6
a large campaign inspired by a country's successful example

6 ____ a large campaign inspired by a country's successful example$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('cb348d98-21ad-5f35-a39d-2b47c162e72f', '2639c4ff-e189-5688-bc06-6d0839e18805', 1, $md$A$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('42cc86bd-5a10-5c60-8d6a-16bf1c2f9df1', '2639c4ff-e189-5688-bc06-6d0839e18805', 2, $md$B$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('221daba5-2586-55d5-9a7e-b54247316449', '2639c4ff-e189-5688-bc06-6d0839e18805', 3, $md$C$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('4a42fead-ad54-5025-affd-c28a80302e1a', '2639c4ff-e189-5688-bc06-6d0839e18805', 4, $md$D$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('31804796-f795-5abb-aa27-f54cbec3ddb0', '2639c4ff-e189-5688-bc06-6d0839e18805', 5, $md$E$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('c975fef2-e3b2-53d0-a7b5-b1fb2d4fa14f', '2639c4ff-e189-5688-bc06-6d0839e18805', 6, $md$F$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('701f26b5-1831-53b7-abf4-728d8cd187f1', '2639c4ff-e189-5688-bc06-6d0839e18805', 7, $md$G$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('98e79d9e-8f6a-590d-b172-aa48caf5a7c6', '2639c4ff-e189-5688-bc06-6d0839e18805', 8, $md$H$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('8e7f06d8-7e03-536a-b244-b65d58daeb37', '6db6fd40-872e-558d-8e71-dd400cda2317', 7, 'TRUE_FALSE_NOT_GIVEN', 'READING', 3, $md$### Question 7

Questions 7-13
Questions 7-13
Do the following statements agree with the information given in Reading Passage?
In boxes 7
-13
on your answer sheet, write
TRUE
if the statement is true
FALSE
if the statement is false
NOT GIVEN
if the information is not given in the passage
7
Photovoltaics are used to store electricity.
8
Since the 1970s, the US government has provided continuous support for the use of photovoltaics on homes.
9
The solar-powered house on Rokko Island is uninhabited.
10
In 1994, the Japanese government was providing half the money required for installing photovoltaics on homes.
11
Germany, Italy, the Netherlands and Australia all have strict goals with regard to greenhouse gas emissions.
12
Residential electricity use is the major source of greenhouse gas emission.
13
Energy-saving measures must now be included in the design of all new homes and improvements to buildings.

7 ____ Photovoltaics are used to store electricity.$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('78841e34-1f28-5e95-a874-338ba3c64c35', '8e7f06d8-7e03-536a-b244-b65d58daeb37', 1, $md$TRUE$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('6e311b46-7407-52ba-8063-542832f137e4', '8e7f06d8-7e03-536a-b244-b65d58daeb37', 2, $md$FALSE$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('e8cf667a-0b9c-5495-9574-dc09efeb4f4a', '8e7f06d8-7e03-536a-b244-b65d58daeb37', 3, $md$NOT GIVEN$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('d6c06bb1-2788-5aee-8e72-9077039637ed', '6db6fd40-872e-558d-8e71-dd400cda2317', 8, 'TRUE_FALSE_NOT_GIVEN', 'READING', 3, $md$### Question 8

Questions 7-13
Questions 7-13
Do the following statements agree with the information given in Reading Passage?
In boxes 7
-13
on your answer sheet, write
TRUE
if the statement is true
FALSE
if the statement is false
NOT GIVEN
if the information is not given in the passage
7
Photovoltaics are used to store electricity.
8
Since the 1970s, the US government has provided continuous support for the use of photovoltaics on homes.
9
The solar-powered house on Rokko Island is uninhabited.
10
In 1994, the Japanese government was providing half the money required for installing photovoltaics on homes.
11
Germany, Italy, the Netherlands and Australia all have strict goals with regard to greenhouse gas emissions.
12
Residential electricity use is the major source of greenhouse gas emission.
13
Energy-saving measures must now be included in the design of all new homes and improvements to buildings.

8 ____ Since the 1970s, the US government has provided continuous support for the use of photovoltaics on homes.$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('4bac7e6f-6559-5daf-ab2c-bdcb187f4a60', 'd6c06bb1-2788-5aee-8e72-9077039637ed', 1, $md$TRUE$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('d07d5807-87ff-5d38-827b-3b5e76f2d42e', 'd6c06bb1-2788-5aee-8e72-9077039637ed', 2, $md$FALSE$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('57ae27ee-f563-5987-a801-9c8598a481cf', 'd6c06bb1-2788-5aee-8e72-9077039637ed', 3, $md$NOT GIVEN$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('03d4136b-5b65-59b2-8ab0-92c774a20564', '6db6fd40-872e-558d-8e71-dd400cda2317', 9, 'TRUE_FALSE_NOT_GIVEN', 'READING', 3, $md$### Question 9

Questions 7-13
Questions 7-13
Do the following statements agree with the information given in Reading Passage?
In boxes 7
-13
on your answer sheet, write
TRUE
if the statement is true
FALSE
if the statement is false
NOT GIVEN
if the information is not given in the passage
7
Photovoltaics are used to store electricity.
8
Since the 1970s, the US government has provided continuous support for the use of photovoltaics on homes.
9
The solar-powered house on Rokko Island is uninhabited.
10
In 1994, the Japanese government was providing half the money required for installing photovoltaics on homes.
11
Germany, Italy, the Netherlands and Australia all have strict goals with regard to greenhouse gas emissions.
12
Residential electricity use is the major source of greenhouse gas emission.
13
Energy-saving measures must now be included in the design of all new homes and improvements to buildings.

9 ____ The solar-powered house on Rokko Island is uninhabited.$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('abcb21c0-2faf-52d7-9320-c109506033eb', '03d4136b-5b65-59b2-8ab0-92c774a20564', 1, $md$TRUE$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('655031d3-e6fc-58a4-b7b0-8a118cb150f4', '03d4136b-5b65-59b2-8ab0-92c774a20564', 2, $md$FALSE$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('8d3606ee-2172-595f-bf23-4b06494d5769', '03d4136b-5b65-59b2-8ab0-92c774a20564', 3, $md$NOT GIVEN$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('c3cd3b2d-2af5-5280-b67e-f479b85fe0f0', '6db6fd40-872e-558d-8e71-dd400cda2317', 10, 'TRUE_FALSE_NOT_GIVEN', 'READING', 4, $md$### Question 10

Questions 7-13
Questions 7-13
Do the following statements agree with the information given in Reading Passage?
In boxes 7
-13
on your answer sheet, write
TRUE
if the statement is true
FALSE
if the statement is false
NOT GIVEN
if the information is not given in the passage
7
Photovoltaics are used to store electricity.
8
Since the 1970s, the US government has provided continuous support for the use of photovoltaics on homes.
9
The solar-powered house on Rokko Island is uninhabited.
10
In 1994, the Japanese government was providing half the money required for installing photovoltaics on homes.
11
Germany, Italy, the Netherlands and Australia all have strict goals with regard to greenhouse gas emissions.
12
Residential electricity use is the major source of greenhouse gas emission.
13
Energy-saving measures must now be included in the design of all new homes and improvements to buildings.

10 ____ In 1994, the Japanese government was providing half the money required for installing photovoltaics on homes.$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('31755243-39d4-5c70-90ed-afe45fd0de6f', 'c3cd3b2d-2af5-5280-b67e-f479b85fe0f0', 1, $md$TRUE$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('6d1549bb-7666-520a-8f35-6ecbd6033af8', 'c3cd3b2d-2af5-5280-b67e-f479b85fe0f0', 2, $md$FALSE$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('68834933-6235-58ec-8433-84c8026e84aa', 'c3cd3b2d-2af5-5280-b67e-f479b85fe0f0', 3, $md$NOT GIVEN$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('27c643e6-b0e2-5ffb-bf44-0f65ab7b44d9', '6db6fd40-872e-558d-8e71-dd400cda2317', 11, 'TRUE_FALSE_NOT_GIVEN', 'READING', 4, $md$### Question 11

Questions 7-13
Questions 7-13
Do the following statements agree with the information given in Reading Passage?
In boxes 7
-13
on your answer sheet, write
TRUE
if the statement is true
FALSE
if the statement is false
NOT GIVEN
if the information is not given in the passage
7
Photovoltaics are used to store electricity.
8
Since the 1970s, the US government has provided continuous support for the use of photovoltaics on homes.
9
The solar-powered house on Rokko Island is uninhabited.
10
In 1994, the Japanese government was providing half the money required for installing photovoltaics on homes.
11
Germany, Italy, the Netherlands and Australia all have strict goals with regard to greenhouse gas emissions.
12
Residential electricity use is the major source of greenhouse gas emission.
13
Energy-saving measures must now be included in the design of all new homes and improvements to buildings.

11 ____ Germany, Italy, the Netherlands and Australia all have strict goals with regard to greenhouse gas emissions.$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('13e21814-4010-5659-a02e-7a2641a30b4c', '27c643e6-b0e2-5ffb-bf44-0f65ab7b44d9', 1, $md$TRUE$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('a03aa80f-4d98-53c6-b0f8-ae544418e850', '27c643e6-b0e2-5ffb-bf44-0f65ab7b44d9', 2, $md$FALSE$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('94fdbff0-417f-57d9-94b2-b75a7435740f', '27c643e6-b0e2-5ffb-bf44-0f65ab7b44d9', 3, $md$NOT GIVEN$md$, true);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('0a79637c-b14c-5f79-a772-c41ed5ca5d1e', '6db6fd40-872e-558d-8e71-dd400cda2317', 12, 'TRUE_FALSE_NOT_GIVEN', 'READING', 4, $md$### Question 12

Questions 7-13
Questions 7-13
Do the following statements agree with the information given in Reading Passage?
In boxes 7
-13
on your answer sheet, write
TRUE
if the statement is true
FALSE
if the statement is false
NOT GIVEN
if the information is not given in the passage
7
Photovoltaics are used to store electricity.
8
Since the 1970s, the US government has provided continuous support for the use of photovoltaics on homes.
9
The solar-powered house on Rokko Island is uninhabited.
10
In 1994, the Japanese government was providing half the money required for installing photovoltaics on homes.
11
Germany, Italy, the Netherlands and Australia all have strict goals with regard to greenhouse gas emissions.
12
Residential electricity use is the major source of greenhouse gas emission.
13
Energy-saving measures must now be included in the design of all new homes and improvements to buildings.

12 ____ Residential electricity use is the major source of greenhouse gas emission.$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('ee85ee66-5c02-5dcd-856f-538d5122ef6a', '0a79637c-b14c-5f79-a772-c41ed5ca5d1e', 1, $md$TRUE$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('b18684fb-db69-5bf5-aa5c-7a9ba1940f81', '0a79637c-b14c-5f79-a772-c41ed5ca5d1e', 2, $md$FALSE$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('2e625328-6c1f-5771-8827-2d4bfb965407', '0a79637c-b14c-5f79-a772-c41ed5ca5d1e', 3, $md$NOT GIVEN$md$, true);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('ee4064ae-b9df-5626-855b-002cac48a679', '6db6fd40-872e-558d-8e71-dd400cda2317', 13, 'TRUE_FALSE_NOT_GIVEN', 'READING', 4, $md$### Question 13

Questions 7-13
Questions 7-13
Do the following statements agree with the information given in Reading Passage?
In boxes 7
-13
on your answer sheet, write
TRUE
if the statement is true
FALSE
if the statement is false
NOT GIVEN
if the information is not given in the passage
7
Photovoltaics are used to store electricity.
8
Since the 1970s, the US government has provided continuous support for the use of photovoltaics on homes.
9
The solar-powered house on Rokko Island is uninhabited.
10
In 1994, the Japanese government was providing half the money required for installing photovoltaics on homes.
11
Germany, Italy, the Netherlands and Australia all have strict goals with regard to greenhouse gas emissions.
12
Residential electricity use is the major source of greenhouse gas emission.
13
Energy-saving measures must now be included in the design of all new homes and improvements to buildings.

13 ____ Energy-saving measures must now be included in the design of all new homes and improvements to buildings.$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('63d67ffd-4ff4-50b0-879d-88eea13614a0', 'ee4064ae-b9df-5626-855b-002cac48a679', 1, $md$TRUE$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('7ad65ebd-e939-5ddd-99e3-45242b8b4202', 'ee4064ae-b9df-5626-855b-002cac48a679', 2, $md$FALSE$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('1a3653a6-69bf-5e19-8f3b-02097031fbdc', 'ee4064ae-b9df-5626-855b-002cac48a679', 3, $md$NOT GIVEN$md$, true);

COMMIT;
