BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DELETE FROM exam_options WHERE "QuestionId" IN (
  SELECT q."Id" FROM exam_questions q
  JOIN exam_sections s ON s."Id" = q."SectionId"
  JOIN exams e ON e."Id" = s."ExamId"
  WHERE e."Slug" = 'ielts-reading-magnetic-therapy-1365'
);
DELETE FROM exam_questions USING exam_sections s, exams e
WHERE exam_questions."SectionId" = s."Id"
  AND s."ExamId" = e."Id"
  AND e."Slug" = 'ielts-reading-magnetic-therapy-1365';
DELETE FROM exam_sections USING exams e
WHERE exam_sections."ExamId" = e."Id"
  AND e."Slug" = 'ielts-reading-magnetic-therapy-1365';
DELETE FROM exams WHERE "Slug" = 'ielts-reading-magnetic-therapy-1365';

INSERT INTO exams ("Id","Slug","Title","DescriptionMd","Category","Level","Status","DurationMin","CreatedAt")
VALUES ('8d23b7f9-8595-5aa7-9891-934967f77e90', 'ielts-reading-magnetic-therapy-1365', $t$Magnetic Therapy$t$, $md$## Magnetic Therapy

Nguồn:
- Test: https://mini-ielts.com/1365/reading/magnetic-therapy
- Solution: https://mini-ielts.com/1365/view-solution/reading/magnetic-therapy$md$, 'IELTS', 'B2', 'PUBLISHED', 20, now());

INSERT INTO exam_sections ("Id","ExamId","Idx","Title","InstructionsMd","AudioUrl","TranscriptMd")
VALUES ('e0cef3da-5d0e-5c3d-a6fc-80f96917e49c', '8d23b7f9-8595-5aa7-9891-934967f77e90', 1, $t$Reading — Magnetic Therapy$t$, $md$Read the passage and answer questions **1–9**.

### Passage: Magnetic Therapy

A

Magnetic therapy, which is a $5-billion market worldwide, is a form of alternative medicine which claims that magnetic fields have healing powers. Magnetic devices that are claimed to be therapeutic include magnetic bracelets, insoles, wrist and knee bands, back and neck braces, and even pillows and mattresses. Their annual sales are estimated at $300 million in the United States and more than a billion dollars globally. They have been advertised to cure a vast array of ills, particularly pain.

B

The therapy works on the principle of balancing electrical energy in the body by pulsating magnetic waves through different parts of the body. The electrical currents generated by magnets increase the blood flow and oxygen which helps to heal many of the ailments. The natural effects of the Earth’s magnetic field are considered to play an essential role in the health of humans and animals. It is generally accepted that our body draws some benefit from the Earth’s magnetic field. To restore the balance within our body allows us to function at our optimum level. For example, when the first astronauts returned to earth sick, NASA concluded that their illness resulted from the lack of a planetary magnetic field in outer space. To resolve the problem, NASA placed magnets in the astronauts’ space suits and space travel vehicles, and astronauts have returned to Earth healthy ever since.

C

Historically it is reported that magnets have been around for an extremely long time. The therapeutic power of magnets was known to physicians in ancient Greece, Egypt and China over 4000 years ago, who used naturally magnetic rock – lodestone – to treat a variety of physical and psychological ailments. Cleopatra the beautiful Egyptian queen was probably the first celebrity to use magnets. It is documented that in order to prevent from aging, she slept on a Lodestone to keep her skin youthful. Ancient Romans also used magnet therapy to treat eye disease.

D

The popularity of magnet therapy in the United States began to rise during the 1800s and soared in the post-Civil War era. Sears-Roebuck advertised magnetic jewelry in its catalog for the healing of virtually any ailment. An Austrian psychoanalyst by the name of Wilhelm Reich immigrated to the United States in 1939 and researched the effects of electromagnetism on humans. Today, Germany, Japan, Israel, Russia and at least 45 other countries consider magnetic therapy to be an official medical procedure for the treatment of numerous ailments, including various inflammatory and neurological problems.

E

For those who practice magnetic therapy, strongly believe that certain ailments can be treated if the patient is exposed to magnetic fields while at the same time there is a strong resentment from the medical establishment and critics claim that most magnets don’t have the strength to affect the various organs and tissues within the body and it is a product of Pseudoscience and is not based on proper research and analysis. There are few reported complications of magnetic therapy and the World Health Organization says a low level of magnetic energy is not harmful. Documented side effects are not life-threatening and include pain, nausea and dizziness that disappeared when the magnets were removed. If considering magnet therapy, as with any medical treatment, it is always advisable to consult one’s regular physician first. Magnet therapy is gaining popularity; however, scientific evidence to support the success of this therapy is lacking. More scientifically sound studies are needed in order to fully understand the effects that magnets can have on the body and the possible benefits or dangers that could result from their use.

F

Researchers at Baylor University Medical Center recently conducted a double-blind study on the use of concentric-circle magnets to relieve chronic pain in 50 post-polio patients. A static magnetic device or a placebo device was applied to the patient’s skin for 45 minutes. The patients were asked to rate how much pain they experienced when a “trigger point was touched.” The researchers reported that the 29 patients exposed to the magnetic device achieved lower pain scores than did the 21 who were exposed to the placebo device. However, this study had significant flaws in their design. Although the groups were said to be selected randomly, the ratio of women to men in the experimental group was twice that of the control group; the age of the placebo group was four years higher than that of the control group; there were just one brief exposure and no systematic follow-up of patients.

G

Magnet therapy is gaining popularity; however, scientific evidence to support the success of this therapy is lacking. More scientifically sound studies are needed in order to fully understand the effects that magnets can have on the body and the possible benefits or dangers that could result from their use.$md$, NULL, NULL);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('820c29aa-4105-5a3b-915c-47fac6de56c3', 'e0cef3da-5d0e-5c3d-a6fc-80f96917e49c', 1, 'MATCHING_HEADING', 'READING', 2, $md$### Question 1

Questions 1-6
Questions 1-6
Reading Passage 1 has seven paragraphs,
A-G
.
Choose the correct heading for paragraphs
A-G
from the list of headings below.
Write the correct number,
i-ix
, in boxes
1-6
on your answer sheet.
List of headings
i
Earth itself as the biggest magnet
ii
The commercial magnetic products
iii
Utilize the power from the natural magnetic field
iv
Early application of the magnet
v
Brief introduction of how the magnetic therapy works
vi
pain-reducing effect
vii
Arguments for and against the therapy
viii
An experiment on post-polio patients
ix
Conditions of magnet use today
1
Paragraph A
2
Paragraph B
3
Paragraph C
4
Paragraph D
5
Paragraph E
6
Paragraph F

1 ____ Paragraph A$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('aace4e9d-7058-5990-a523-0e175c50a833', '820c29aa-4105-5a3b-915c-47fac6de56c3', 1, $md$i$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('342430f7-bdf8-55f8-b588-e684550f74b8', '820c29aa-4105-5a3b-915c-47fac6de56c3', 2, $md$ii$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('73d3593b-84ea-5b4a-93ff-5c513c4390ef', '820c29aa-4105-5a3b-915c-47fac6de56c3', 3, $md$iii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('17aab179-e958-5b67-aa10-05fc556cdbf8', '820c29aa-4105-5a3b-915c-47fac6de56c3', 4, $md$iv$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('dceb0898-7a22-5333-b30e-89bc80568e4f', '820c29aa-4105-5a3b-915c-47fac6de56c3', 5, $md$v$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('2bbf64a9-93a8-5250-8d89-2a65d2d39a26', '820c29aa-4105-5a3b-915c-47fac6de56c3', 6, $md$vi$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('874a4412-9433-5384-b83b-3edfeac76888', '820c29aa-4105-5a3b-915c-47fac6de56c3', 7, $md$vii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('449a635a-18d3-5b6e-9687-f4b6cfb3c73f', '820c29aa-4105-5a3b-915c-47fac6de56c3', 8, $md$viii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('68f8158e-64b3-5d65-a55d-1bc19aba31ef', '820c29aa-4105-5a3b-915c-47fac6de56c3', 9, $md$ix$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('2a26e5a3-6719-5d05-a285-f11bacf458ed', 'e0cef3da-5d0e-5c3d-a6fc-80f96917e49c', 2, 'MATCHING_HEADING', 'READING', 2, $md$### Question 2

Questions 1-6
Questions 1-6
Reading Passage 1 has seven paragraphs,
A-G
.
Choose the correct heading for paragraphs
A-G
from the list of headings below.
Write the correct number,
i-ix
, in boxes
1-6
on your answer sheet.
List of headings
i
Earth itself as the biggest magnet
ii
The commercial magnetic products
iii
Utilize the power from the natural magnetic field
iv
Early application of the magnet
v
Brief introduction of how the magnetic therapy works
vi
pain-reducing effect
vii
Arguments for and against the therapy
viii
An experiment on post-polio patients
ix
Conditions of magnet use today
1
Paragraph A
2
Paragraph B
3
Paragraph C
4
Paragraph D
5
Paragraph E
6
Paragraph F

2 ____ Paragraph B$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('5b90c5d1-f1c7-592e-8880-bec7900b94f7', '2a26e5a3-6719-5d05-a285-f11bacf458ed', 1, $md$i$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('b96083f0-e1fe-5e8e-b1e7-7bc78b11a783', '2a26e5a3-6719-5d05-a285-f11bacf458ed', 2, $md$ii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('0a190e6e-6a7c-598f-b925-65039b865731', '2a26e5a3-6719-5d05-a285-f11bacf458ed', 3, $md$iii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('150d1452-0d21-57ca-b2b2-fd44e255e93b', '2a26e5a3-6719-5d05-a285-f11bacf458ed', 4, $md$iv$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('13ad7ac2-d6ae-574e-9e82-811a51b20845', '2a26e5a3-6719-5d05-a285-f11bacf458ed', 5, $md$v$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('09d427cf-d660-5e4d-a6ab-eeaf55cf0bcf', '2a26e5a3-6719-5d05-a285-f11bacf458ed', 6, $md$vi$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('0b6fff30-21c7-5c35-b326-05481e77b35f', '2a26e5a3-6719-5d05-a285-f11bacf458ed', 7, $md$vii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('80ed24d0-8100-542d-b265-bcf2c4053428', '2a26e5a3-6719-5d05-a285-f11bacf458ed', 8, $md$viii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('8518a5ce-2f66-52ef-a9e1-1cdb34d36500', '2a26e5a3-6719-5d05-a285-f11bacf458ed', 9, $md$ix$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('619541da-6fbb-5896-a201-b902b4e74f14', 'e0cef3da-5d0e-5c3d-a6fc-80f96917e49c', 3, 'MATCHING_HEADING', 'READING', 2, $md$### Question 3

Questions 1-6
Questions 1-6
Reading Passage 1 has seven paragraphs,
A-G
.
Choose the correct heading for paragraphs
A-G
from the list of headings below.
Write the correct number,
i-ix
, in boxes
1-6
on your answer sheet.
List of headings
i
Earth itself as the biggest magnet
ii
The commercial magnetic products
iii
Utilize the power from the natural magnetic field
iv
Early application of the magnet
v
Brief introduction of how the magnetic therapy works
vi
pain-reducing effect
vii
Arguments for and against the therapy
viii
An experiment on post-polio patients
ix
Conditions of magnet use today
1
Paragraph A
2
Paragraph B
3
Paragraph C
4
Paragraph D
5
Paragraph E
6
Paragraph F

3 ____ Paragraph C$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('01d12bc5-f201-5755-a2d4-36dfc83ad725', '619541da-6fbb-5896-a201-b902b4e74f14', 1, $md$i$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('7d48f93a-bfe4-5ca6-bb4b-fe03ca39efe7', '619541da-6fbb-5896-a201-b902b4e74f14', 2, $md$ii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('ab0130f6-672a-53b9-9aff-26a781c09d73', '619541da-6fbb-5896-a201-b902b4e74f14', 3, $md$iii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('349cf2e2-21b7-56cc-b3e2-9be3d549c450', '619541da-6fbb-5896-a201-b902b4e74f14', 4, $md$iv$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('21865215-7731-5979-a93c-4f2a85c1d403', '619541da-6fbb-5896-a201-b902b4e74f14', 5, $md$v$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('a61118ef-53b7-53e7-9fa9-d07f336ecbef', '619541da-6fbb-5896-a201-b902b4e74f14', 6, $md$vi$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('e4daf2a0-d16d-513a-8331-070bbf592ea8', '619541da-6fbb-5896-a201-b902b4e74f14', 7, $md$vii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('58fd079b-51d2-5133-bcda-859567e21568', '619541da-6fbb-5896-a201-b902b4e74f14', 8, $md$viii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('f466d07e-b503-51cd-8b5e-29fe165d19a2', '619541da-6fbb-5896-a201-b902b4e74f14', 9, $md$ix$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('79bc4c5d-89cd-516f-ba02-1599ed3b3881', 'e0cef3da-5d0e-5c3d-a6fc-80f96917e49c', 4, 'MATCHING_HEADING', 'READING', 2, $md$### Question 4

Questions 1-6
Questions 1-6
Reading Passage 1 has seven paragraphs,
A-G
.
Choose the correct heading for paragraphs
A-G
from the list of headings below.
Write the correct number,
i-ix
, in boxes
1-6
on your answer sheet.
List of headings
i
Earth itself as the biggest magnet
ii
The commercial magnetic products
iii
Utilize the power from the natural magnetic field
iv
Early application of the magnet
v
Brief introduction of how the magnetic therapy works
vi
pain-reducing effect
vii
Arguments for and against the therapy
viii
An experiment on post-polio patients
ix
Conditions of magnet use today
1
Paragraph A
2
Paragraph B
3
Paragraph C
4
Paragraph D
5
Paragraph E
6
Paragraph F

4 ____ Paragraph D$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('8cafb4be-c34e-5738-a19d-035dc75de503', '79bc4c5d-89cd-516f-ba02-1599ed3b3881', 1, $md$i$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('3824a68e-7a48-5b16-a1c7-ccd5880d4138', '79bc4c5d-89cd-516f-ba02-1599ed3b3881', 2, $md$ii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('c84d8814-07ed-5fb6-ad1b-464ae3432984', '79bc4c5d-89cd-516f-ba02-1599ed3b3881', 3, $md$iii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('c6e26cb0-f73b-5af9-b909-8565c9706bf6', '79bc4c5d-89cd-516f-ba02-1599ed3b3881', 4, $md$iv$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('546b2ac4-3614-5e83-bb8b-1c216a7032b9', '79bc4c5d-89cd-516f-ba02-1599ed3b3881', 5, $md$v$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('597dcbf0-ad12-568a-aecc-f35a86d7a7b0', '79bc4c5d-89cd-516f-ba02-1599ed3b3881', 6, $md$vi$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('b02d5388-518c-58e2-8ca3-7b07416c9663', '79bc4c5d-89cd-516f-ba02-1599ed3b3881', 7, $md$vii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('5459c0cf-6c10-5fcd-8d6d-53613f9a6c19', '79bc4c5d-89cd-516f-ba02-1599ed3b3881', 8, $md$viii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('22bc7c75-5a80-53d0-962b-136cae7f7eb5', '79bc4c5d-89cd-516f-ba02-1599ed3b3881', 9, $md$ix$md$, true);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('9bc77ef0-e519-5768-bcc0-654d31c763c5', 'e0cef3da-5d0e-5c3d-a6fc-80f96917e49c', 5, 'MATCHING_HEADING', 'READING', 3, $md$### Question 5

Questions 1-6
Questions 1-6
Reading Passage 1 has seven paragraphs,
A-G
.
Choose the correct heading for paragraphs
A-G
from the list of headings below.
Write the correct number,
i-ix
, in boxes
1-6
on your answer sheet.
List of headings
i
Earth itself as the biggest magnet
ii
The commercial magnetic products
iii
Utilize the power from the natural magnetic field
iv
Early application of the magnet
v
Brief introduction of how the magnetic therapy works
vi
pain-reducing effect
vii
Arguments for and against the therapy
viii
An experiment on post-polio patients
ix
Conditions of magnet use today
1
Paragraph A
2
Paragraph B
3
Paragraph C
4
Paragraph D
5
Paragraph E
6
Paragraph F

5 ____ Paragraph E$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('85341907-abd8-547a-be85-db239af25e84', '9bc77ef0-e519-5768-bcc0-654d31c763c5', 1, $md$i$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('74688b3d-1cb8-5cf5-aaf0-07aae673f334', '9bc77ef0-e519-5768-bcc0-654d31c763c5', 2, $md$ii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('5f34ee83-fc98-5ea0-975b-316a4cc64e6d', '9bc77ef0-e519-5768-bcc0-654d31c763c5', 3, $md$iii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('908111c9-ca0d-5245-863c-9219ee26ce23', '9bc77ef0-e519-5768-bcc0-654d31c763c5', 4, $md$iv$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('ed80b21b-df01-51c1-aea7-763f35bbe5a9', '9bc77ef0-e519-5768-bcc0-654d31c763c5', 5, $md$v$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('e66bd5d8-810e-5669-836a-72c75619a685', '9bc77ef0-e519-5768-bcc0-654d31c763c5', 6, $md$vi$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('28d522c5-c454-554b-bb83-e2bdd8c58ba1', '9bc77ef0-e519-5768-bcc0-654d31c763c5', 7, $md$vii$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('10256c84-b320-550f-8eb4-4e8d81da25f2', '9bc77ef0-e519-5768-bcc0-654d31c763c5', 8, $md$viii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('293badf3-ca83-5f6f-8a37-fd93d9efaa90', '9bc77ef0-e519-5768-bcc0-654d31c763c5', 9, $md$ix$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('f8287234-2c0a-52dc-93db-e3b8c5321741', 'e0cef3da-5d0e-5c3d-a6fc-80f96917e49c', 6, 'MATCHING_HEADING', 'READING', 3, $md$### Question 6

Questions 1-6
Questions 1-6
Reading Passage 1 has seven paragraphs,
A-G
.
Choose the correct heading for paragraphs
A-G
from the list of headings below.
Write the correct number,
i-ix
, in boxes
1-6
on your answer sheet.
List of headings
i
Earth itself as the biggest magnet
ii
The commercial magnetic products
iii
Utilize the power from the natural magnetic field
iv
Early application of the magnet
v
Brief introduction of how the magnetic therapy works
vi
pain-reducing effect
vii
Arguments for and against the therapy
viii
An experiment on post-polio patients
ix
Conditions of magnet use today
1
Paragraph A
2
Paragraph B
3
Paragraph C
4
Paragraph D
5
Paragraph E
6
Paragraph F

6 ____ Paragraph F$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('4ca74d21-e7dd-5f99-8ec4-11deacfc5436', 'f8287234-2c0a-52dc-93db-e3b8c5321741', 1, $md$i$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('5522eebf-74c2-5bfe-8a4e-e05a57cb9238', 'f8287234-2c0a-52dc-93db-e3b8c5321741', 2, $md$ii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('cb99db79-1b83-5a2a-8ae0-b470ab4d7cc2', 'f8287234-2c0a-52dc-93db-e3b8c5321741', 3, $md$iii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('3116a8e6-23e6-5148-9a0f-abb8b5147ae5', 'f8287234-2c0a-52dc-93db-e3b8c5321741', 4, $md$iv$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('18dc4c2d-15c1-5648-b91d-93333c9446c9', 'f8287234-2c0a-52dc-93db-e3b8c5321741', 5, $md$v$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('ca5b0509-8464-5767-be99-089aa2fe2ed0', 'f8287234-2c0a-52dc-93db-e3b8c5321741', 6, $md$vi$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('35c0b477-a380-57cb-a57e-e90ecaf79520', 'f8287234-2c0a-52dc-93db-e3b8c5321741', 7, $md$vii$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('343df46f-436f-5e99-aab0-e496a0c3f62e', 'f8287234-2c0a-52dc-93db-e3b8c5321741', 8, $md$viii$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('266468f5-0f21-5e5f-bf45-f11a2bb8f965', 'f8287234-2c0a-52dc-93db-e3b8c5321741', 9, $md$ix$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('b7852ec7-4a83-5faf-bfff-558323d0e146', 'e0cef3da-5d0e-5c3d-a6fc-80f96917e49c', 11, 'MULTIPLE_CHOICE_SINGLE', 'READING', 4, $md$### Question 11

Questions 11-13
Questions 11-13
Complete each sentence with the correct ending,
A-F
, below.
Write the correct letters,
A-F
, in boxes
11-13
on your answer sheet.
11
The first NASA astronauts’ sickness
12
According to the WHO, under the physician’s instruction, a small amount of magnetic energy
13
The author holds that in order to fully understand the magnetic effects, we
A
has no negative side effect.
B
resulted from physical ailment.
C
should have more sophisticated studies
D
is exposed to the placebo device.
E
must select the subjects randomly.
F
came from the absence of a magnetic field.

11 ____ The first NASA astronauts’ sickness$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('1f0d6d67-3318-5ca0-ad02-081e6c5efc1d', 'b7852ec7-4a83-5faf-bfff-558323d0e146', 1, $md$A$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('6246eed9-4ca1-52a8-a100-c8576980d89e', 'b7852ec7-4a83-5faf-bfff-558323d0e146', 2, $md$B$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('517eb6b3-a923-5aa0-b446-6155072c4542', 'b7852ec7-4a83-5faf-bfff-558323d0e146', 3, $md$C$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('23e96fda-121b-5d3d-a563-476d1730dd80', 'b7852ec7-4a83-5faf-bfff-558323d0e146', 4, $md$D$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('a6946aee-f5f7-587e-9a5f-95d00783ae99', 'b7852ec7-4a83-5faf-bfff-558323d0e146', 5, $md$E$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('2177c59c-3299-56da-be0f-b4321c7649b9', 'b7852ec7-4a83-5faf-bfff-558323d0e146', 6, $md$F$md$, true);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('37f95368-bdd0-5a36-8651-1ec4194c8a6b', 'e0cef3da-5d0e-5c3d-a6fc-80f96917e49c', 12, 'MULTIPLE_CHOICE_SINGLE', 'READING', 4, $md$### Question 12

Questions 11-13
Questions 11-13
Complete each sentence with the correct ending,
A-F
, below.
Write the correct letters,
A-F
, in boxes
11-13
on your answer sheet.
11
The first NASA astronauts’ sickness
12
According to the WHO, under the physician’s instruction, a small amount of magnetic energy
13
The author holds that in order to fully understand the magnetic effects, we
A
has no negative side effect.
B
resulted from physical ailment.
C
should have more sophisticated studies
D
is exposed to the placebo device.
E
must select the subjects randomly.
F
came from the absence of a magnetic field.

12 ____ According to the WHO, under the physician’s instruction, a small amount of magnetic energy$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('90bff7f7-8704-58c9-9d33-b0f583d8de60', '37f95368-bdd0-5a36-8651-1ec4194c8a6b', 1, $md$A$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('46ad8512-86f7-59e2-8ece-acf2c737a1eb', '37f95368-bdd0-5a36-8651-1ec4194c8a6b', 2, $md$B$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('cb73053b-d34f-5fe9-80b9-f8ee4b83713a', '37f95368-bdd0-5a36-8651-1ec4194c8a6b', 3, $md$C$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('a721a4b8-fb48-5bd3-aaf7-5204671194e0', '37f95368-bdd0-5a36-8651-1ec4194c8a6b', 4, $md$D$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('da7d7105-9f7f-5ffc-8fe3-50af4e82b9ff', '37f95368-bdd0-5a36-8651-1ec4194c8a6b', 5, $md$E$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('3b17f4c1-f74e-59cd-8bc0-bab65da3a880', '37f95368-bdd0-5a36-8651-1ec4194c8a6b', 6, $md$F$md$, false);

INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd")
VALUES ('db9bcea8-c4ea-5ff5-95b5-27f8627d5589', 'e0cef3da-5d0e-5c3d-a6fc-80f96917e49c', 13, 'MULTIPLE_CHOICE_SINGLE', 'READING', 4, $md$### Question 13

Questions 11-13
Questions 11-13
Complete each sentence with the correct ending,
A-F
, below.
Write the correct letters,
A-F
, in boxes
11-13
on your answer sheet.
11
The first NASA astronauts’ sickness
12
According to the WHO, under the physician’s instruction, a small amount of magnetic energy
13
The author holds that in order to fully understand the magnetic effects, we
A
has no negative side effect.
B
resulted from physical ailment.
C
should have more sophisticated studies
D
is exposed to the placebo device.
E
must select the subjects randomly.
F
came from the absence of a magnetic field.

13 ____ The author holds that in order to fully understand the magnetic effects, we$md$, NULL);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('6eb5e9a6-cfb8-5b52-bea1-8a7ea87578c4', 'db9bcea8-c4ea-5ff5-95b5-27f8627d5589', 1, $md$A$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('173f1e06-a926-5f76-84b6-3640be0af28c', 'db9bcea8-c4ea-5ff5-95b5-27f8627d5589', 2, $md$B$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('8a5c41ef-c586-5686-8b99-9b7fe36651e0', 'db9bcea8-c4ea-5ff5-95b5-27f8627d5589', 3, $md$C$md$, true);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('c74f59f1-08d2-50b0-b091-cbd74171d9da', 'db9bcea8-c4ea-5ff5-95b5-27f8627d5589', 4, $md$D$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('945738db-dad8-516f-bb9a-d26b6f8971d9', 'db9bcea8-c4ea-5ff5-95b5-27f8627d5589', 5, $md$E$md$, false);
INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect")
VALUES ('b84ef20c-4ca1-5f55-9142-85b22d7800b4', 'db9bcea8-c4ea-5ff5-95b5-27f8627d5589', 6, $md$F$md$, false);

COMMIT;
