-- ============================================
-- IELTS Exam Data Import SQL
-- Generated: 2025-12-24T02:02:51.255351
-- Source: mini-ielts.com
-- Title: Carbon Capture and Storage
-- ============================================

BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Cleanup existing data for slug: mini-ielts-reading-carbon-capture-and-storage
DELETE FROM exam_options WHERE "QuestionId" IN (
  SELECT q."Id" FROM exam_questions q
  JOIN exam_sections s ON s."Id" = q."SectionId"
  JOIN exams e ON e."Id" = s."ExamId"
  WHERE e."Slug" = 'mini-ielts-reading-carbon-capture-and-storage'
);
DELETE FROM exam_questions USING exam_sections s, exams e
WHERE exam_questions."SectionId" = s."Id"
  AND s."ExamId" = e."Id"
  AND e."Slug" = 'mini-ielts-reading-carbon-capture-and-storage';
DELETE FROM exam_sections USING exams e
WHERE exam_sections."ExamId" = e."Id"
  AND e."Slug" = 'mini-ielts-reading-carbon-capture-and-storage';
DELETE FROM exams
WHERE "Slug" = 'mini-ielts-reading-carbon-capture-and-storage';

DO $$
DECLARE
  exam_id uuid := gen_random_uuid();
  sec1 uuid := gen_random_uuid();
  qid uuid;
BEGIN

  INSERT INTO exams ("Id","Slug","Title","DescriptionMd","Category","Level","Status","DurationMin","ImageUrl","UpdatedAt")
  VALUES (
    exam_id,
    'mini-ielts-reading-carbon-capture-and-storage',
    'Carbon Capture and Storage',
    'IELTS Reading Practice Test from IELTS Mentor',
    'IELTS',
    'B2',
    'PUBLISHED',
    20,
    'https://res.cloudinary.com/df41zs8il/image/upload/v1766530822/ielts/1506013216casestudy-icon_resiz_896f64e5f7c0.jpg',
    now()
  );

  INSERT INTO exam_sections ("Id","ExamId","Idx","Title","InstructionsMd","PassageMd")
  VALUES (
    sec1,
    exam_id,
    1,
    'Reading Passage - Carbon Capture and Storage',
    E'**Questions 1-2:**\nChoose the correct letter **A**, **B**, **C**, or **D**.\nWrite the correct letter in boxes 1-2 on your answer sheet.\n\n---\n\n**Questions 3-8:**\nLabel the diagrams on the following page.\nWrite the correct letter, **A-H**, in boxes 3-8 on your answer sheet.\n\n**Options:**\n- A - CO2\n- B - Coal\n- C - Natural gas\n- D - Oil\n- E - Saline aquifer\n- F - Steam-driven turbines\n- G - Syngas\n- H - Syngas-driven turbines\n\n---\n\n**Questions 9-14:**\nComplete the table below.\nChoose **NO MORE THAN THREE WORDS AND/OR A NUMBER** from the passage for each answer.',
    E'# Carbon Capture and Storage\n\n## Carbon capture\n\nWhile CO2 storage has been accomplished, its capture from power plants remains largely hypothetical, although CCS plants throughout Western Europe and North America are on the drawing board.\n\nThere are three main forms of CCS: pre-combustion, post-combustion, and oxy-firing. In a 2012 paper from the US Congressional Budget Office (CBO), post-combustion capture was viewed most favourably since existing power plants can be retrofitted with it, whereas pre-combustion and oxy-firing mean the construction of entirely new plants. However, pre-combustion and oxy-firing remove more CO2 than post-combustion and generate more electricity.\n\nPost-combustion capture means CO2 is separated from gas after coal is burnt but before electricity is generated, while in oxy-firing, coal is combusted in pure oxygen. In pre-combustion, as in an Integrated Gasification Combined Cycle system (IGCC), oxygen, coal, and water are burnt together to produce a synthetic gas called Syngas – mainly hydrogen – which drives two sets of turbines, firstly gas-driven ones, then, as the cooling Syngas travel through water, steam-driven ones. Emissions from this process contain around ten percent of the CO2 that burning coal produces.\n\n## The pros and cons of CCS\n\nSeveral countries are keen to scale up CCS as it may reduce carbon emissions quickly, and powerful lobby groups for CCS exist among professionals in mining and engineering. Foundries and refineries that produce steel and emit carbon may also benefit, and the oil and gas industry is interested because power-plant equipment consumes their products. In addition, recent clean energy acts in many countries mandate that a percentage of electricity be generated by renewables or by more energy-efficient systems, like CCS.\n\nAs with desalination, where powerful lobbies wield influence, states sometimes find it easier to engage in large projects involving a few players rather than change behaviours on a more scattered household scale. Furthermore, replacing coal with zero-emission photovoltaic (PV) cells to produce solar energy would require covering an area nearly 20,720 square kilometres, roughly twice the size of Lebanon or half of Denmark.\n\nStill, there are many reservations about CCS. Principally, it is enormously expensive: conservative estimates put the electricity it generates at more than five times the current retail price. As consumers are unlikely to want to bear this price hike, massive state subsidies would be necessary for CCS to work.\n\nThe capital outlay of purchasing equipment for retrofitting existing power plants is high enough, but the energy needed to capture CO2 means one third more coal must be burnt, and building new CCS plants is at least 75% more expensive than retro-fitting.\n\nSome CCS technology is untried, for example, the Syngas-driven turbines in an IGCC system have not been used on an industrial scale. Post capture, CO2 must be compressed into a supercritical liquid for transport and storage, which is also costly. The Qatar Carbonates and Carbon Storage Research Centre predicts 700 million barrels per day of this liquid would be produced if CCS were adopted modestly. It is worth noting that current oil production is around 85 million barrels per day, so CCS would produce eleven times more waste for burial than oil that was simultaneously being extracted.\n\nSequestration has been used successfully, but there are limited coal and oil fields where optimal conditions exist. In rock that is too brittle, earthquakes could release the CO2. Moreover, proposals to store CO2 in saline aquifers are just that – proposals: sequestration has never been attempted in aquifers.\n\nMost problematic of all, CCS reduces carbon emissions but does not end them, rendering it a medium-term solution.\n\n## Alternatives\n\nThere are at least four reasonably-priced alternatives to CCS. Firstly, conventional pulverised coal power plants are undergoing redesign so more electricity can be produced from less coal. Before coal is phased out – as ultimately it will have to be – these plants could be more cost-effective. Secondly, hybrid plants using natural gas and coal could be built. Thirdly, natural gas could be used on its own. Lastly, solar power is fast gaining credibility.\n\nIn all this, an agreed measure of cost for electricity generation must be used. This is called a levelized cost of energy (LCOE) – an average cost of producing electricity over the lifetime of a power plant, including construction, financing, and operation, although pollution is not counted. In 2012, the CBO demonstrated that a new CCS plant had an LCOE of about $0.09-0.15 per kilowatt-hour (kWh), but according to the US Energy Information Administration, the LCOE from a conventional natural gas power plant without CCS is $0.0686/kWh, making it the cheapest way to produce clean energy.\n\nSolar power costs are falling rapidly. In 2013, the Los Angeles Department of Water and Power reported that energy via a purchase agreement from a large solar plant was $0.095/kWh, and Greentech Media, a company that reviews environmental projects, found a 2014 New Mexico solar project that generates power for $0.0849/kWh.\n\nStill, while so much coal and so many coal-fired plants exist, decommissioning them all may not be realistic. Whatever happens, the conundrum of cheap power and clean air may remain unsolved for some time.\n\n---\n\n## Diagram: Carbon Dioxide Sequestration (Questions 3-8)\n\n![Carbon Dioxide Sequestration Diagram 1](https://ieltstrainingonline.com/wp-content/uploads/2019/10/06-IELTS-Reading-q27-40-1.jpg)\n\n![Carbon Dioxide Sequestration Diagram 2](https://ieltstrainingonline.com/wp-content/uploads/2019/10/06-IELTS-Reading-q27-40-2.jpg)\n\nLabel the diagrams with letters **A-H**:\n- **A** CO2\n- **B** Coal\n- **C** Natural gas\n- **D** Oil\n- **E** Saline aquifer\n- **F** Steam-driven turbines\n- **G** Syngas\n- **H** Syngas-driven turbines\n\nComplete the labels:\n- **3** _______\n- **4** _______\n- **5** _______\n- **6** _______\n- **7** _______\n- **8** _______'
  );

  qid := gen_random_uuid();
  INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd","MatchPairs")
  VALUES (
    qid,
    sec1,
    1,
    'MULTIPLE_CHOICE_SINGLE',
    'READING',
    2,
    'What is the global average for electricity generated from coal?',
    '',
    NULL
  );
  INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect") VALUES (gen_random_uuid(), qid, 1, 'A. 41%', true);
  INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect") VALUES (gen_random_uuid(), qid, 2, 'B. 44%', false);
  INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect") VALUES (gen_random_uuid(), qid, 3, 'C. 49%', false);
  INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect") VALUES (gen_random_uuid(), qid, 4, 'D. 70%', false);

  qid := gen_random_uuid();
  INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd","MatchPairs")
  VALUES (
    qid,
    sec1,
    2,
    'MULTIPLE_CHOICE_SINGLE',
    'READING',
    2,
    'What does the average American pay each month for CO2 produced by a local power plant?',
    '',
    NULL
  );
  INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect") VALUES (gen_random_uuid(), qid, 1, 'A. $17', false);
  INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect") VALUES (gen_random_uuid(), qid, 2, 'B. $80', false);
  INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect") VALUES (gen_random_uuid(), qid, 3, 'C. $113', false);
  INSERT INTO exam_options ("Id","QuestionId","Idx","ContentMd","IsCorrect") VALUES (gen_random_uuid(), qid, 4, 'D. Nothing', true);

  qid := gen_random_uuid();
  INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd","BlankAcceptTexts")
  VALUES (
    qid,
    sec1,
    3,
    'DIAGRAM_LABEL',
    'READING',
    2,
    'Diagram label 3 _______',
    '',
    '{"blank-q3": ["A", "a"]}'::jsonb
  );

  qid := gen_random_uuid();
  INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd","BlankAcceptTexts")
  VALUES (
    qid,
    sec1,
    4,
    'DIAGRAM_LABEL',
    'READING',
    2,
    'Diagram label 4 _______',
    '',
    '{"blank-q4": ["C", "c"]}'::jsonb
  );

  qid := gen_random_uuid();
  INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd","BlankAcceptTexts")
  VALUES (
    qid,
    sec1,
    5,
    'DIAGRAM_LABEL',
    'READING',
    2,
    'Diagram label 5 _______',
    '',
    '{"blank-q5": ["E", "e"]}'::jsonb
  );

  qid := gen_random_uuid();
  INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd","BlankAcceptTexts")
  VALUES (
    qid,
    sec1,
    6,
    'DIAGRAM_LABEL',
    'READING',
    2,
    'Diagram label 6 _______',
    '',
    '{"blank-q6": ["B", "b"]}'::jsonb
  );

  qid := gen_random_uuid();
  INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd","BlankAcceptTexts")
  VALUES (
    qid,
    sec1,
    7,
    'DIAGRAM_LABEL',
    'READING',
    2,
    'Diagram label 7 _______',
    '',
    '{"blank-q7": ["G", "g"]}'::jsonb
  );

  qid := gen_random_uuid();
  INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd","BlankAcceptTexts")
  VALUES (
    qid,
    sec1,
    8,
    'DIAGRAM_LABEL',
    'READING',
    2,
    'Diagram label 8 _______',
    '',
    '{"blank-q8": ["F", "f"]}'::jsonb
  );

  qid := gen_random_uuid();
  INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd","BlankAcceptTexts")
  VALUES (
    qid,
    sec1,
    9,
    'SUMMARY_COMPLETION',
    'READING',
    2,
    'CCS may cut _______ in a short time',
    '',
    '{"blank-q9": ["carbon emissions"]}'::jsonb
  );

  qid := gen_random_uuid();
  INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd","BlankAcceptTexts")
  VALUES (
    qid,
    sec1,
    10,
    'SUMMARY_COMPLETION',
    'READING',
    2,
    '_______ in labour, industry, and states already support CCS',
    '',
    '{"blank-q10": ["powerful lobbies"]}'::jsonb
  );

  qid := gen_random_uuid();
  INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd","BlankAcceptTexts")
  VALUES (
    qid,
    sec1,
    11,
    'SUMMARY_COMPLETION',
    'READING',
    2,
    'Alternatives, like _______ energy, take up vast amounts of space',
    '',
    '{"blank-q11": ["solar"]}'::jsonb
  );

  qid := gen_random_uuid();
  INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd","BlankAcceptTexts")
  VALUES (
    qid,
    sec1,
    12,
    'SUMMARY_COMPLETION',
    'READING',
    2,
    'Therefore, CCS would need _______',
    '',
    '{"blank-q12": ["massive state subsidies"]}'::jsonb
  );

  qid := gen_random_uuid();
  INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd","BlankAcceptTexts")
  VALUES (
    qid,
    sec1,
    13,
    'SUMMARY_COMPLETION',
    'READING',
    2,
    'Some CCS technology is _______',
    '',
    '{"blank-q13": ["untried"]}'::jsonb
  );

  qid := gen_random_uuid();
  INSERT INTO exam_questions ("Id","SectionId","Idx","Type","Skill","Difficulty","PromptMd","ExplanationMd","BlankAcceptTexts")
  VALUES (
    qid,
    sec1,
    14,
    'SUMMARY_COMPLETION',
    'READING',
    2,
    'LCOE for natural gas = _______',
    '',
    '{"blank-q14": ["$0.0686", "kWh"]}'::jsonb
  );


END$$;


COMMIT;