-- ============================================
-- IELTS Writing Task 1 Data Import (writing-service)
-- Generated: 2025-12-23T15:47:17.464438
-- Source: ielts-mentor.com
-- Title: Construction Work Is Being Done Where You Live
-- ============================================

BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Cleanup existing data with same title
DELETE FROM "writing_exams" WHERE "Title" = E'Construction Work Is Being Done Where You Live';

-- Insert into writing_exams table
INSERT INTO "writing_exams" (
  "Id",
  "Title", 
  "TaskText",
  "ExamType",
  "Level",
  "Tags",
  "ModelAnswers",
  "CreatedAt",
  "CreatedBy"
)
VALUES (
  gen_random_uuid(),
  E'Construction Work Is Being Done Where You Live',
  E'You should spend about\n20\nminutes on this task.\nSome construction work is being done on the street where you live for the last couple of days. The noise from the work is loud and it disturbs you.\nWrite a letter to your local council complaining about the noise. In your letter,\nintroduce yourself\nexplain how the noise is causing problems to you\nsuggest solutions to the problem\nWrite at least\n150\nwords.\nYou do\nNOT\nneed to write any addresses.\nBegin your letter as follows:\nDear Sir or Madam,',
  1,
  'B2',
  'ielts,letter,task1,gt',
  E'["Dear Sir or Madam,\\nI am writing this letter to formally lodge a complaint about the uncomfortable, and sometimes unbearable, noise which keeps coming from the ongoing road construction works in the adjacent areas to my house.\\nTo introduce myself a little, my name is Nicholas Fauci, and I live on Lindsay Street, next to Fairmont Shopping Centre in the Hampshire area.\\nThe road repair works, I am talking about, has been going on for almost one week with the use of heavy vehicles and construction tools, from morning to late night, sometimes. Naturally, the continuous sounds, generated by heavy machinery and tools, are causing a lot of trouble for many residents in our neighbourhood. Some people in our area are already complaining about a bad headache. The school-going children are also struggling to concentrate on their studies. Not to mention, of course, the trouble with sleeping has also become a major concern for many residents in our locality because of the noises.\\nAs a solution to this ongoing problem, I would like to request you to employ additional manpower to finish the construction works as soon as possible and save us from the trouble of these unbearable noises.\\nYours faithfully,\\nNicholas Fauci\\n1\\n1\\n1\\n1\\n1\\n1\\n1\\n1\\n1\\n1\\nRating 4.95 (10 Votes)\\nIELTS Letter Writing\\nGT Writing Task 1\\nPrev\\nNext\\nName\\nPreview\\nSend\\nReset\\nCancel\\nRSS\\nMd. Iftekhar Alam\\n5 years 6 months\\nI got a lot of IELTS"]'::jsonb,
  now(),
  '00000000-0000-0000-0000-000000000000'
);

COMMIT;
