// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using attempt_service.Infrastructure.Persistence;

#nullable disable

namespace attempt_service.Migrations
{
    [DbContext(typeof(AttemptDbContext))]
    [Migration("20251228145038_AddBookmarkContextFields")]
    partial class AddBookmarkContextFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("attempt_service.Domain.Entities.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSec")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("PaperJson")
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("RawScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("ScaledScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExamId", "Status")
                        .HasDatabaseName("idx_attempt_exam_status");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_attempt_user_status");

                    b.ToTable("attempts", (string)null);
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.AttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AwardedPoints")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("SelectedOptionIds")
                        .HasColumnType("uuid[]");

                    b.Property<string>("TextAnswer")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("uq_attempt_answer_attempt_question");

                    b.ToTable("attempt_answer", (string)null);
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectedText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_note_created");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_note_user");

                    b.HasIndex("UserId", "AttemptId")
                        .HasDatabaseName("idx_note_user_attempt");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.PlacementResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Band")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ListeningCorrect")
                        .HasColumnType("integer");

                    b.Property<int>("ListeningTotal")
                        .HasColumnType("integer");

                    b.Property<int>("ReadingCorrect")
                        .HasColumnType("integer");

                    b.Property<int>("ReadingTotal")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SpeakingBand")
                        .HasColumnType("numeric");

                    b.Property<string>("SpeakingGradeJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("TotalCorrect")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WritingBand")
                        .HasColumnType("numeric");

                    b.Property<string>("WritingGradeJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .IsUnique();

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("placement_result", (string)null);
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.StudyGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("FocusSkills")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("StudyHoursPerDay")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)");

                    b.Property<decimal>("TargetBandScore")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_study_goal_user");

                    b.ToTable("study_goals", (string)null);
                });

            modelBuilder.Entity("attempt_service.Domains.Entities.QuestionBookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("QuestionContent")
                        .HasColumnType("text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionType")
                        .HasColumnType("text");

                    b.Property<string>("Skill")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_bookmark_created");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_bookmark_user");

                    b.HasIndex("UserId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("uq_bookmark_user_question");

                    b.ToTable("question_bookmarks", (string)null);
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.AttemptAnswer", b =>
                {
                    b.HasOne("attempt_service.Domain.Entities.Attempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.PlacementResult", b =>
                {
                    b.HasOne("attempt_service.Domain.Entities.Attempt", "Attempt")
                        .WithMany("PlacementResults")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.Attempt", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("PlacementResults");
                });
#pragma warning restore 612, 618
        }
    }
}
