// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using attempt_service.Infrastructure.Persistence;

#nullable disable

namespace attempt_service.Migrations
{
    [DbContext(typeof(AttemptDbContext))]
    [Migration("20260826092933_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("attempt_service.Domain.Entities.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("PaperJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("RawScore")
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("ScaledScore")
                        .HasColumnType("numeric(4,1)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_attempts_user_id");

                    b.HasIndex("UserId", "ExamId")
                        .HasDatabaseName("ix_attempts_user_exam");

                    b.ToTable("attempts", (string)null);
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.AttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("AnswerJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AwardedPoints")
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("RagFeedbackJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("ix_attempt_answers_attempt_id");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique();

                    b.ToTable("attempt_answers", (string)null);
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectedText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notes_user_id");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.PlacementResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Band")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ListeningCorrect")
                        .HasColumnType("integer");

                    b.Property<int>("ListeningTotal")
                        .HasColumnType("integer");

                    b.Property<int>("ReadingCorrect")
                        .HasColumnType("integer");

                    b.Property<int>("ReadingTotal")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SpeakingBand")
                        .HasColumnType("numeric");

                    b.Property<string>("SpeakingGradeJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("TotalCorrect")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WritingBand")
                        .HasColumnType("numeric");

                    b.Property<string>("WritingGradeJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("ix_placement_results_attempt_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_placement_results_user_id");

                    b.ToTable("placement_results", (string)null);
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.QuestionBookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("QuestionContent")
                        .HasColumnType("text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionType")
                        .HasColumnType("text");

                    b.Property<string>("Skill")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "QuestionId");

                    b.ToTable("question_bookmarks", (string)null);
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.StudyGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("FocusSkills")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("StudyHoursPerDay")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TargetBandScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_study_goals_user_id");

                    b.ToTable("study_goals", (string)null);
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.AttemptAnswer", b =>
                {
                    b.HasOne("attempt_service.Domain.Entities.Attempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.PlacementResult", b =>
                {
                    b.HasOne("attempt_service.Domain.Entities.Attempt", "Attempt")
                        .WithMany("PlacementResults")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("attempt_service.Domain.Entities.Attempt", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("PlacementResults");
                });
#pragma warning restore 612, 618
        }
    }
}
