services:
  auth-service:
    build:
      context: ../services/auth-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - CONNECTIONSTRING__DEFAULT=Host=database;Port=5432;Database=appdb;Username=appuser;Password=apppassword
      - PUBLIC_GOOGLE_CLIENT_ID=806530195444-6jrbcfonq01nuk9k66rnc31fib6rqgt2.apps.googleusercontent.com
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTIONSTRING__REDIS=redis:6379, abortConnect=false
    networks: 
      - backend
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    ports: ["5432:5432"]
    networks:
      - backend
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7.4-alpine
    container_name: redis
    command: [
      "redis-server",
      "--save", "",                 # tắt RDB
      "--appendonly", "no",         # tắt AOF
      "--maxmemory", "128mb",       # giới hạn bộ nhớ Redis
      "--maxmemory-policy", "allkeys-lru",
      "--databases", "1",           # 1 DB là đủ cho hầu hết case
      "--port", "6379"
      ]
    ports:
      - "6379:6379"  
    networks:
      - backend
    tmpfs:
      - /data:size=64m
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 2s
      retries: 5

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
