// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using writing_service.Infrastructure.Persistence;

#nullable disable

namespace writing_service.Migrations
{
    [DbContext(typeof(WritingDbContext))]
    [Migration("20251120212440_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("writing_service.Domains.Entities.WritingEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CoherenceAndCohesionBand")
                        .HasColumnType("double precision");

                    b.Property<string>("CoherenceAndCohesionComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("GrammaticalRangeAndAccuracyBand")
                        .HasColumnType("double precision");

                    b.Property<string>("GrammaticalRangeAndAccuracyComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImprovedParagraph")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("LexicalResourceBand")
                        .HasColumnType("double precision");

                    b.Property<string>("LexicalResourceComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OverallBand")
                        .HasColumnType("double precision");

                    b.Property<string>("PromptSchemaVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawLlmJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuggestionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TaskResponseBand")
                        .HasColumnType("double precision");

                    b.Property<string>("TaskResponseComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("writing_evaluation", (string)null);
                });

            modelBuilder.Entity("writing_service.Domains.Entities.WritingExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("ExamType")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("TaskText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("writing_exams", (string)null);
                });

            modelBuilder.Entity("writing_service.Domains.Entities.WritingSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EssayNormalized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EssayRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExamType")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaskTextSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TimeSpentSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("writing_submissions", (string)null);
                });

            modelBuilder.Entity("writing_service.Domains.Entities.WritingEvaluation", b =>
                {
                    b.HasOne("writing_service.Domains.Entities.WritingSubmission", "WritingSubmission")
                        .WithMany("WritingEvaluations")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WritingSubmission");
                });

            modelBuilder.Entity("writing_service.Domains.Entities.WritingSubmission", b =>
                {
                    b.HasOne("writing_service.Domains.Entities.WritingExam", "WritingExam")
                        .WithMany("WritingSubmissions")
                        .HasForeignKey("ExamId");

                    b.Navigation("WritingExam");
                });

            modelBuilder.Entity("writing_service.Domains.Entities.WritingExam", b =>
                {
                    b.Navigation("WritingSubmissions");
                });

            modelBuilder.Entity("writing_service.Domains.Entities.WritingSubmission", b =>
                {
                    b.Navigation("WritingEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
